### ISSUE TITLE
Please add max.com

### ISSUE THREAD

**Issue by CHJ85** [aminomancer/Netflix-Marathon-Pausable#15]
Hi there. Please add max.com now that HBO Max has changed to Max in the US.
Same address structure though (play.max.com/video/watch).
Oh... And also if you could add starzplay.com (Starz outside the US). Same address structure as starz.com.

**Comment by aminomancer** [comment]
Thanks for the report. I will need to take some time to investigate when I get some time, since it looks like they have changed the site considerably.

**Comment by CHJ85** [comment]
The API is rewritten from scratch it seems. However, the video player code hasn't changed a bit. Even the url structure is the same (as far as I can tell). Btw. HBO Max is still going to be around for another couple years around the world. So don't remove that.

**Comment by aminomancer** [comment]
The code turned out to be quite different, but I think v5.7.0 covers everything we handled on play.hbomax.com.

I noted that play.max.com can show ads that disable skip/seek controls, in addition to the ones that are hard-coded into the video. We're able to skip the latter just fine with the same code that skips intros and credits. But apparently there's a special kind of mandatory ad shown to some users that blocks you from skipping or seeking away from it.

I don't know if play.hbomax.com did this too, since I think my account is ads-free or something, as I can't get any ads to appear on any video. Anyway, I looked into how skip/seek works under the hood and disabling those controls when an ad is playing is just done with a flag. The internal `skip` method is just as public as the `requestSkip` method that calls it. So if we're able to access one, we should be able to access the other. I'm just not sure if we can access either.

Also, it seems to require a timestamp to skip to. That can probably be found somewhere but I didn't look for it very hard since I can't get ads to appear. Pretty hard to figure out without any testing capability. It's something I'll hopefully revisit in the future, and if this causes problems for you, file another bug report and hopefully I'll get around to it if/when I find a way to get ads to appear. Or maybe a volunteer will submit a PR.

Anyway, since there wasn't any logic for bypassing such ads on the old play.hbomax.com, I don't really consider it a blocker for this.

**Comment by aminomancer** [comment]
Btw, I forgot about your request for starzplay.com. I have no way of testing how this works (same with starz.ca for Canada) so I'll treat these sites exactly the same way starz is treated. If you can do some testing with v5.7.1 and share results in #16 that would be great.

**Comment by CHJ85** [comment]
Thanks for all your work.
Starzplay is working fine.
However... Because I do not live in Canada, I won't be able to test that one. But I'm sure it's the same.
