### ISSUE TITLE
url matching goes wrong

### ISSUE THREAD

**Issue by 1roha** [aminomancer/Netflix-Marathon-Pausable#5]
since 5.1.5 (to latest 5.2.1) url matching is not working properly for primevideo.
i'm using violentmonkey 2.13.0 on firefox 93.0

fixed by rerolling to 5.1.4

**Comment by aminomancer** [comment]
primevideo.com? Try updating to 5.2.3, I added that URL back

**Comment by aminomancer** [comment]
> 
> 
> Hi, I think I have the same error when I'm trying to install it on Greasemonkey from Greasy Fork and it says: `Ignore model @match http*://*.amazon.ae/* because : Error: @match: Invalid protocol (http*:) specified.` I'm not sure what it means but hope it helps.

That's not the same issue. This bug is about the removal of `http*://*.primevideo.com/*` from the match rules in 5.1 a couple weeks ago. The URL was added back in 5.2.3 a few days ago.

Your complaint is due to a deficiency in Greasemonkey. It does not support the `http*` scheme syntax. In Greasemonkey, `*` has the same meaning that `http*` has in newer script managers. That is, it returns http or https, not ftp, file, etc. But in Violentmonkey for instance, `*` can mean any scheme.

The readme and code comments do clearly indicate that Greasemonkey is not recommended. Even ignoring the matching issue, several features are impossible to support in any version of Greasemonkey, especially where the user configuration and menu commands are concerned. All the important async functions from GM 4.x are implemented in Violentmonkey anyway, without losing the sync versions. So I always recommend using Violentmonkey, or at least Tampermonkey. FireMonkey works too.
