### ISSUE TITLE
Skips episodes on Prime video

### ISSUE THREAD

**Issue by rayman89** [aminomancer/Netflix-Marathon-Pausable#7]
When this script is enabled it sometimes skips episodes when re watching a series. Sometimes skips 2 or more.

**Comment by aminomancer** [comment]
Thanks, I'll take a look. Been a while since I've used prime video

**Comment by aminomancer** [comment]
I guess it's possible that it's caused by this:
```
if ((store = this.qry(".atvwebplayersdk-nextupcard-button"))) {
  // next episode
  await sleep(400);
  this.clk(store);
}
```
We're waiting 400ms before clicking, but the interval rate is 300ms. So, if the timing is just right, invocation 1 happens, starting a 400ms timer, then 300ms later, invocation 2 happens, starting another 400ms timer. Then 100ms later, invocation 1 clicks the button. Then 300ms later, invocation 2 tries to click the same button. Maybe it still exists for some reason.

So I'm going to change it from a static interval to a timeout. We'll invoke the site-specific handler, wait for it to complete, and then set a timer for the next check. So normally it will invoke every 300ms but for some of the special items that I set delays for, the next check won't begin until those delays have finished. So that way we can't have 2 instances of the site-specific handler awaiting at the same time.

However, I'm not entirely convinced that's the problem, because there's still 300ms of time between invocation 1's click and invocation 2's click. That should be enough time for the button to disappear after being clicked. I'm unable to reproduce the problem, so I can't check. I tried rewatching a series where Amazon had my saved position set to the end of every episode. But when I hit play, it didn't resume at the end of the episode, it started over from the beginning.

So when I start Episode 1, I have to skip to the end of the duration, even though I had already watched that episode. And then Marathon correctly sees the next-up button, clicks it, and now I'm on Episode 2. And Episode 2 also starts from the beginning. So I'm not able to get a situation where the next-up button is visible, we click it, we go to the next episode, and then the next-up button is immediately visible again. Maybe there are some other conditions that need to occur for that to happen.

But in any case I'm trying to put in some precautionary measures that may or may not help prevent such a scenario. If you could give me more details about exactly what's going on then I might be able to do more. For example, did you change the Interval rate in the settings? What happens when the video starts? Are you sitting through the entire episode or does it start at the end of the duration? If you're on Episode 1, does it jump to Episode 2, and then immediately spot the next-up button and jump to Episode 3? Or does it somehow jump straight from Episode 1 to Episode 3?

**Comment by rayman89** [comment]
Yes I tried increasing the interval up to 1500ms but that did not fix it. The skipping occurs at the beginning of loading a new episode so lets say I finished episode 8 so the screens goes black and the title for episode 9 appears and the loading wheel shows up. Then the title for episode 10 appears and starts loading.
I think it has to do with skipping the trailers amazon has of other series when it tries to skip that it also skips the episode as well.

**Comment by aminomancer** [comment]
Can you tell me more about the environment? Locale? Browser? Script manager? Any examples of a series/episode where this happens? Otherwise, I can try sending a debug version of the script for you to try so we can collect some information... Unfortunately I have no idea how to make Amazon show trailers anymore. It hasn't played a trailer for me in like 2 years.

**Comment by rayman89** [comment]
Firefox browser latest release version. Locale en-US. Prime video is in Spanish LATAM. I'm using tamper monkey. You can also send the debug if this does not help.
Why the trailers don't play for you anymore?

**Comment by aminomancer** [comment]
Are you still seeing this bug @rayman89?
