### ISSUE TITLE
Add Support to hotstar.com

### ISSUE THREAD

**Issue by inalam** [aminomancer/Netflix-Marathon-Pausable#9]
will you add support to [https://www.hotstar.com/id](url) it may has similiarity with disney+. thanks with this beautiful extension you've created 😉

**Comment by aminomancer** [comment]
Thanks for the feedback. I wasn't able to use the website, it says to go to hotstar.com/us but that site says it's shut down. I wasn't able to access the site through a VPN either, probably since most services like this block known VPN IP ranges. But if you or someone else who can access hotstar.com wants to add support, I'll accept a PR.
